// Builds public/pro-data.js, the data behind the Pro features:
//   icm - push/fold Nash solutions at the bubble and a final table (ICM), 3-9 players, 10 and 15bb
//   ev  - for every shove-or-fold spot the site teaches (chip EV and ICM), what the wrong action
//         costs with each hand, in big blinds
//   v3  - facing an all-in 3-bet at 25bb: the exact calling range (pot odds against the 3-bet
//         range, using the full equity table) and what a wrong call or fold costs
// Rerun after changing ranges in public/engine.js:  node tools/build-pro.js   (about 3 minutes)
const fs = require('fs'), path = require('path'), vm = require('vm');
const { makeGame, evaluate, solve } = require('./icm');
const M = require('./data/matrix.json');
const root = path.join(__dirname, '..');

// Payouts in % of the prize pool for 1st..9th at a final table. The bubble pays the top N-1 of
// these and nothing to the last player; a final table of N pays the top N.
const FT = [25, 17, 12.5, 9.5, 7.5, 6, 5, 4, 3.3];
const payFor = (stage, n) => stage === 'ft' ? FT.slice(0, n) : [...FT.slice(0, n - 1), 0];

// Run the site's engine in a sandbox, with the Pro data built so far visible to it.
function engine(PRO) {
  const ctx = { localStorage: { getItem() { return null; }, setItem() {} }, console, PRO };
  vm.createContext(ctx);
  vm.runInContext(fs.readFileSync(path.join(root, 'public', 'engine.js'), 'utf8') + `
;this.E={set(n,d,st){N=n;D=d;STAGE=st||'cev';buildScenarios();},scn:()=>SCN,actionOf,HANDS,NASH,unpack,TABLES,DEPTHS,combos};`, ctx);
  return ctx.E;
}

const EVA = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const enc = x => { x = Math.max(0, x); const v = x < 3.05 ? Math.round(x * 10) : Math.min(63, 31 + Math.round((x - 3) * 2)); return EVA[Math.min(v, 63)]; };
const hex = f => { let s = ''; for (let k = 0; k < 169; k += 4) { let v = 0; for (let b = 0; b < 4; b++) if (k + b < 169 && f[k + b] >= 0.5) v |= 1 << b; s += v.toString(16); } return s; };
const pure = (E, hx) => { const set = E.unpack(hx); return E.HANDS.map(k => (set.has(k) ? 1 : 0)); };

const PRO = { icm: {}, ev: {}, v3: {} };
let E = engine(PRO);

// 1. ICM solutions
for (const stage of ['bub', 'ft']) for (const S of [10, 15]) for (let n = 3; n <= 9; n++) {
  const t = Date.now(), r = solve(makeGame(n, S, payFor(stage, n)), M, 600);
  const o = { s: r.shove.map(hex), c: {} };
  for (let i = 0; i < n - 1; i++) for (let j = i + 1; j < n; j++) o.c[`${i}-${j}`] = hex(r.call[i][j]);
  PRO.icm[`${stage}-${n}-${S}`] = o;
  console.log(`ICM ${stage} ${n}-handed ${S}bb`, Date.now() - t + 'ms');
}
E = engine(PRO);

// 2. Cost of each wrong push/fold decision, against the (rounded) strategies the charts show
for (const stage of ['cev', 'bub', 'ft']) for (const S of [10, 15]) for (let n = 2; n <= 9; n++) {
  if (stage !== 'cev' && n < 3) continue;
  const nash = stage === 'cev' ? E.NASH[`${n}-${S}`] : PRO.icm[`${stage}-${n}-${S}`];
  const shove = nash.s.map(h => pure(E, h)), call = [];
  for (let i = 0; i < n - 1; i++) { call[i] = []; for (let j = i + 1; j < n; j++) call[i][j] = pure(E, nash.c[`${i}-${j}`]); }
  const ev = evaluate(makeGame(n, S, stage === 'cev' ? null : payFor(stage, n)), M, shove, call);
  E.set(n, S, stage);
  const names = E.TABLES[n], out = {};
  for (const s of E.scn()) {
    const d = s.type === 'rfi' ? ev.shove[names.indexOf(s.hero)] : ev.call[names.indexOf(s.opener)][names.indexOf(s.hero)];
    out[s.id] = E.HANDS.map((k, h) => enc(E.actionOf(s, k) === 'fold' ? -d[h] : d[h])).join('');
  }
  PRO.ev[`${stage}-${n}-${S}`] = out;
}
console.log('EV tables done');

// 3. Facing an all-in 3-bet: call when equity against the 3-bet range beats the price
for (let n = 2; n <= 9; n++) for (const S of E.DEPTHS.filter(d => d > 15)) {
  E.set(n, S);
  const out = {};
  for (const s of E.scn().filter(x => x.type === 'v3' && x.threeTo >= S)) {
    const T = E.scn().find(x => x.id === `vs-${s.opener}-${s.hero}`).sets['3bet'], Ti = E.HANDS.map(k => T.has(k));
    const flags = [], cost = [];
    E.HANDS.forEach((k, h) => {
      let w = 0, e = 0; for (let g = 0; g < 169; g++) if (Ti[g]) { w += M.W[h][g]; e += M.W[h][g] * M.EQ[h][g]; }
      const diff = w ? (e / w) * (s.pot + s.call) - s.call : -s.call;
      flags.push(diff > 0 ? 1 : 0); cost.push(Math.abs(diff));
    });
    out[s.id] = { c: hex(flags), e: cost.map(enc).join('') };
  }
  if (Object.keys(out).length) PRO.v3[`${n}-${S}`] = out;
}
console.log('3-bet shove calls done');

const file = path.join(root, 'public', 'pro-data.js');
fs.writeFileSync(file, `/* Preflop IQ Pro data. GENERATED by tools/build-pro.js; do not edit.
   icm: bubble and final-table push/fold Nash solutions; ev: cost of each wrong push/fold decision;
   v3: exact calls against an all-in 3-bet at 25bb. */
const PRO=${JSON.stringify(PRO)};
`);
console.log('Wrote public/pro-data.js', (fs.statSync(file).size / 1024).toFixed(0) + 'KB');
